<!-- Log in page -->
<section>
      <h2>Identifiez-vous</h2>
      <div class="background">
            <div class="userdata">
                  <div class="panel">
                        <form action="login.php" method="POST">
                              <div>
                                    <label for="email">Email</label>
                                    <input type="email" id="email" name="email" placeholder="Adresse email" required>
                              </div>
                              <div>
                                    <label for="password">Mot de passe</label>
                                    <input type="password" id="password" name="password" placeholder="Mot de passe" required>
                              </div>
                              <div class="form-button">
                                    <button class="submit" type="submit"><i class="fas fa-sign-in-alt fa-2x"></i></button>
                              </div>
                        </form>
                  </div>
            </div>
      </div>
      <!-- Link to register page -->
      <div class="register-link">
            <p>Pas encore inscrit ? Inscrivez-vous <a class="submit" href="register.php">ici</a> !</p>
      </div>
</section>