<!-- Register page view -->
<section>
      <h2>Inscription</h2>
      <div class="background">
            <div class="userdata">
                  <div class="panel">
                        <form action="register.php" method="POST">
                              <label for="username">Nom d'utilisateur</label>
                              <input type="text" id="username" name="username" placeholder="Nom d'utilisateur" pattern=".{4,}" title="Doit contenir 4 caractères min" required>

                              <label for="email">Email</label>
                              <input type="text" id="email" name="email" placeholder="Adresse email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" title="Doit contenir une adresse email valide exemple: characters@characters.domain" required>

                              <label for="password">Mot de passe</label>
                              <input type="password" id="password" name="password" placeholder="Mot de passe" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Doit contenir 8 caractères minimum, dont un chiffre et une lettre majuscule" required>

                              <label for="firstname">Prénom</label>
                              <input type="text" id="firstname" name="firstname" placeholder="Prénom" required>

                              <label for="lastname">Nom</label>
                              <input type="text" id="lastname" name="lastname" placeholder="Nom" required>

                              <label for="birthdate">Date de naissance</label>
                              <input type="text" id="birthdate" name="birthdate" placeholder="Date de naissance" required>

                              <label for="phone">Téléphone</label>
                              <input type="text" id="phone" name="phone" placeholder="Téléphone" required>

                              <label for="address">Adresse</label>
                              <input type="text" id="address" name="address" placeholder="Adresse" required>

                              <label for="city">Ville</label>
                              <input type="text" id="city" name="city" placeholder="Ville" required>

                              <label for="zipcode">Code postal</label>
                              <input type="text" id="zipcode" name="zipcode" placeholder="Code postal" required>

                              <div class="form-button">
                                    <button class="submit" name="submit" type="submit"><i class="register fas fa-user-plus fa-2x"></i></button>
                              </div>
                        </form>
                  </div>
            </div>
      </div>
</section>