<!-- If log in, display user personnal data and his products registered -->
<?php if (Session::isConnected() && $_SESSION['auth']) : ?>
      <!-- Display user's personal data -->
      <section>
            <h2 id="personal-data">Données personnelles</h2>
            <div class="background">
                  <div class="userdata">
                        <div class="panel">
                              <label for="username">Pseudo</label>
                              <input id="username" value="<?= $_SESSION['auth']['username']; ?>" disabled></input>

                              <label for="email">Email</label>
                              <input id="email" value="<?= $_SESSION['auth']['email']; ?>" disabled></input>

                              <label for="firstname">Prénom</label>
                              <input id="firstname" value="<?= $_SESSION['auth']['firstname']; ?>" disabled></input>

                              <label for="lastname">Nom</label>
                              <input id="lastname" value="<?= $_SESSION['auth']['lastname']; ?>" disabled></input>

                              <label for="birthdate">Date de naissance</label>
                              <input id="birthdate" value="<?= $_SESSION['auth']['birthdate']; ?>" disabled></input>

                              <label for="phone">Téléphone</label>
                              <input id="phone" value="<?= $_SESSION['auth']['phone']; ?>" disabled></input>


                              <label for="address">Adresse postale</label>
                              <input id="address" value="<?= $_SESSION['auth']['address']; ?>" disabled></input>

                              <label for="city">Commune</label>
                              <input id="city" value="<?= $_SESSION['auth']['city']; ?>" disabled></input>

                              <label for="zipcode">Code postal</label>
                              <input id="zipcode" value="<?= $_SESSION['auth']['zipcode']; ?>" disabled></input>
                        </div>
                        <div class="article-icons">
                              <div class="border-icons">
                                    <a href="updateUser.php?id=<?= $_SESSION['auth']['id']; ?>"><i class="edit fas fa-edit fa-2x"></i></a>
                              </div>
                        </div>
                  </div>
            </div>
      </section>

      <!-- PRODUCT SECTION -->
      <section>
            <h2 id="personal-post">Vos annonces</h2>
            <div class="background">
                  <div class="grid-flex-container">
                        <!-- Display user's products data into a <table> -->
                        <?php foreach ($products as $product) : ?>
                              <div class="item">
                                    <article>
                                          <img src="<?= strtok($product['files'], ',') ?>" alt="<?= $product['product_name'] ?>" />
                                          <hr>
                                          <div>
                                                <h3><?= $product['product_name'] ?></h3>
                                                <div>
                                                      <strong><?= $product['price'] . ' €' ?></strong>
                                                </div>
                                                <div>
                                                      <p><i class="fas fa-clock"></i><?= ' ' . $product['created_date'] ?>
                                                      <p>
                                                </div>
                                                <hr>
                                                <div>
                                                      <h4>Critères</h4>
                                                      <div class="flex">
                                                            <div class="product-criteria">
                                                                  <h5>Etat :</h5>
                                                                  <p><?= $product['status'] ?></p>
                                                            </div>
                                                            <div class="product-criteria">
                                                                  <h5>Catégorie :</h5>
                                                                  <p><?= $product['name'] ?></p>
                                                            </div>
                                                      </div>
                                                </div>
                                                <hr>
                                                <div class="article-icons">
                                                      <div class="border-icons">
                                                            <a href="deleteProduct.php?id=<?= intval($product['product_id']) ?>"><i class="trash fas fa-trash-alt fa-2x"></i></a>
                                                      </div>
                                                      <div class="border-icons">
                                                            <a href="updateProduct.php?id=<?= intval($product['product_id']) ?>"><i class="edit fas fa-edit fa-2x"></i></a>
                                                      </div>
                                                      <div class="border-icons">
                                                            <a href="productPage.php?id=<?= $product['product_id']; ?>"><i class="eye fas fa-eye fa-2x"></i></a>
                                                      </div>
                                                </div>
                                          </div>
                                    </article>
                              </div>
                        <?php endforeach ?>
                  </div>
                  <div>
      </section>

      <!-- MESSAGE SECTION -->
      <section>
            <!-- Received message -->
            <h2 id="received-msg">Vos messages reçus</h2>
            <div class="background">
                  <div class="message-grid">
                        <!-- Display user's messages data -->
                        <div class="userdata">
                              <?php foreach ($sendedMsg as $messenger) : ?>
                                    <?php if ($messenger['receiver_id'] == $_SESSION['auth']['id']) : ?>
                                          <div class="date">
                                                <div>
                                                      <strong><?= substr($messenger['created_date'], 0, 10) ?></strong>
                                                </div>
                                                <div>
                                                      <strong><?= substr($messenger['created_date'], 10, 17) ?></strong>
                                                </div>
                                          </div>
                                          <div>
                                                <div class="message-title">
                                                      <span class="bolder">Objet :</span>
                                                      <span class="title"><?= $messenger['title'] ?></span>
                                                </div>
                                                <div class="message-inbox">
                                                      <div class="message-options">
                                                            <span class="bolder"><?= $messenger['username']; ?> à vous</span>
                                                            <!-- Delete message icon -->
                                                            <a href="deleteMessage.php?id=<?= intval($messenger['id']) ?>">
                                                                  <i class="trash fas fa-trash-alt message-trash"></i>
                                                            </a>
                                                            <!-- Reply message icon -->
                                                            <a href="messagePage.php?id=<?= intval($messenger['id']); ?>">
                                                                  <i class="reply fas fa-reply message-reply"></i>
                                                            </a>
                                                            <div class="message-text-container">
                                                                  <a class="message-page-link" href="messagePage.php?id=<?= intval($messenger['id']); ?>">
                                                                        <span class="message">
                                                                              <?= substr($messenger['content'], 0, 100) . "&hellip;" ?></span>
                                                                  </a>
                                                            </div>
                                                      </div>
                                                </div>
                                          </div>
                                    <?php endif; ?>
                              <?php endforeach; ?>
                        </div>
                  </div>
            </div>

            <!-- Sended message -->
            <h2 id="sent-msg">Vos messages envoyés</h2>
            <div class="background">
                  <div class="message-grid">
                        <!-- Display user's messages data -->
                        <div class="userdata">
                              <?php foreach ($receivedMsg as $messenger) : ?>
                                    <?php if ($messenger['sender_id'] == $_SESSION['auth']['id']) : ?>
                                          <div class="date">
                                                <div>
                                                      <strong><?= substr($messenger['created_date'], 0, 10) ?></strong>
                                                </div>
                                                <div>
                                                      <strong><?= substr($messenger['created_date'], 10, 17) ?></strong>
                                                </div>
                                          </div>
                                          <div>
                                                <div class="message-title">
                                                      <span class="bolder">Objet :</span>
                                                      <span class="title"><?= $messenger['title'] ?></span>
                                                </div>
                                                <div class="message-inbox">
                                                      <div class="message-options">
                                                            <span class="bolder">Vous à <?= $messenger['username']; ?></span>
                                                            <!-- Delete message -->
                                                            <a href="deleteMessage.php?id=<?= intval($messenger['id']) ?>">
                                                                  <i class="trash fas fa-trash-alt message-trash"></i>
                                                            </a>
                                                            <!-- Full message view -->
                                                            <div class="message-text-container">
                                                                  <a class="message-page-link" href="messageDisplay.php?id=<?= intval($messenger['id']); ?>">
                                                                        <span class="message">
                                                                              <?= substr($messenger['content'], 0, 100) . "&hellip;" ?></span>
                                                                  </a>
                                                            </div>
                                                      </div>
                                                </div>
                                          </div>
                                    <?php endif; ?>
                              <?php endforeach; ?>
                        </div>
                  </div>
            </div>
      </section>
<?php endif; ?>